### ISSUE TITLE
Getting error Class 'App\Http\Controllers\PDF' not found

### ISSUE THREAD

**Issue by mohinithorat** [praem90/laravel-mpdf#1]

**Comment by praem90** [comment]
Please add the below line in `config/app.php` to resolve the PDF facade.

```
'PDF' => Praem90\PDF\Facade::class,
```

**Comment by mohinithorat** [comment]
I am using Laravel 5, and I included it in bootstrap/app.php file.

$app->register(Praem90\PDF\ServiceProvider::class);
 $app->withFacades(true, [Praem90\PDF\Facade::class => 'PDF']);

**Comment by praem90** [comment]
Hope you are working in laravel version > 5.1

Updating the `bootstrap/app.php` file isn't a good practice and not recommended too. Please follow the recommended way and it should work fine.

https://laravel.com/docs/5.0/facades#creating-facades
https://laravel.com/docs/5.0/providers#registering-providers

**Comment by mohinithorat** [comment]
I am using Laravel/lumen framework, I cannot see app.php file in config folder.

**Comment by praem90** [comment]
I've tested this package with Lumen 5.5 and its working fine.
Check this out.
https://github.com/praem90/test-mpdf-with-lumen

**Comment by praem90** [comment]
Just clone the repo and install dependencies.
Run the following command in the root directory, 
```
php -S localhost:9000 -t public
```
Visit localhost:9000 and you can view the test PDF

**Comment by mohinithorat** [comment]
Hi,

I am facing another prob. If I try to loadHTML, it does take too much time.

**Comment by mohinithorat** [comment]
Hi,

I am facing another prob. If I try to loadHTML, it does take too much time.

  $html =  '<tr style="color:#808080;">
                      <td style="font-size:12px;border-collapse: collapse; border: 0;border-bottom: 1px solid #d7d7d7;padding: 8px 10px;color:#808080;">Client Phone Number</td>
                      <td style="font-size:14px;border-collapse: collapse; border: 0;border-bottom: 1px solid #d7d7d7;padding: 8px 10px;text-align:right;color:#000">'.'PHONE_NUMBER'.'</td>
                  </tr>
                <tr style="color:#808080;border-bottom: 1px solid #a4a4a4;">
                      <td style="font-size:12px;border-collapse: collapse; border: 0;border-bottom: 1px solid #d7d7d7;padding: 8px 10px;color:#808080;">Client Email</td>
                      <td style="font-size:12px;border-collapse: collapse; border: 0;border-bottom: 1px solid #d7d7d7;padding: 8px 10px;text-align:right;color:#000">'.'Email'.'</td>
                  </tr>
                 <tr style="color:#808080;border-bottom: 1px solid #a4a4a4;">
                      <td style="font-size:12px;border-collapse: collapse; border: 0;border-bottom: 1px solid #d7d7d7;padding: 8px 10px;color:#808080;">Pet Name</td>
                      <td style="font-size:12px;border-collapse: collapse; border: 0;border-bottom: 1px solid #d7d7d7;padding: 8px 10px;text-align:right;color:#000">'.'Pet option_details'.'</td>
                  </tr>
              <tr style="color:#808080;border-bottom: 1px solid #a4a4a4;">
                      <td style="font-size:12px;border-collapse: collapse; border: 0;border-bottom: 1px solid #d7d7d7;padding: 8px 10px;color:#808080;">Ask.Vet Text Session Date/Time</td>
                      <td style="font-size:12px;border-collapse: collapse; border: 0;border-bottom: 1px solid #d7d7d7;padding: 8px 10px;text-align:right;color:#000">'.'concludeTime'.'</td>
                  </tr>
                 <tr style="color:#808080;border-bottom: 1px solid #a4a4a4;">
                      <td style="font-size:12px;border-collapse: collapse; border: 0;border-bottom: 1px solid #d7d7d7;padding: 8px 10px;color:#808080;">'.'CLINIC_NAME'.' Location</td>
                      <td style="font-size:12px;border-collapse: collapse; border: 0;border-bottom: 1px solid #d7d7d7;padding: 8px 10px;text-align:right;color:#000">'.'CLINIC_LOCATION'.'</td>
                 </tr>';
 $mpdf = PDF::loadHtml($html);
    $mpdf->Output(\URL::to('').'/thread_pdfs/pdf.pdf');

**Comment by praem90** [comment]
You should provide system path (`storage_path('thread_pdfs/pdf.pdf')`) but `URL::to()` provides url (`http://localhost`).

**Comment by mohinithorat** [comment]
It still takes time.
